export const type2ops = {
    ANYTYPE: ['e', 'n', 's', 'c', 'k', 'l', 'g', 'm', 'n', 'h', 'u', 'x', 'w'],
    BASE64BINARY: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    BOOLEAN: ['e', 'n'],
    DATE: ['e', 'n', 'l', 'g', 'm', 'h'],
    DATETIME: ['e', 'n', 'l', 'g', 'm', 'h'],
    DOUBLE: ['e', 'n', 'l', 'g', 'm', 'h'],
    ID: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    INTEGER: ['e', 'n', 'l', 'g', 'm', 'h'],
    INT: ['e', 'n', 'l', 'g', 'm', 'h'],
    STRING: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'w'],
    TIME: ['e', 'n', 'l', 'g', 'm', 'h'],
    ADDRESS: ['w', 'y'],
    ADDRESSCOUNTRY: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    ADDRESSSTATE: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    AUTONUMBER: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    BIRTHDAY: ['e', 'n', 'l', 'g', 'm', 'h'],
    BITVECTOR: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    CONTENT: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    CURRENCY: ['e', 'n', 'l', 'g', 'm', 'h'],
    CURRENCYCODE: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    DATACATEGORYGROUPREFERENCE: ['e', 'n'],
    DATEONLY: ['e', 'n', 'l', 'g', 'm', 'h'],
    DIVISION: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    DUEDATE: ['e', 'n', 'l', 'g', 'm', 'h'],
    DYNAMICENUM: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    EMAIL: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    ENCRYPTEDTEXT: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    ENTITYID: ['e', 'n', 's'],
    ENUMORID: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    EXTERNALID: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    FAX: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    HTMLMULTILINETEXT: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    HTMLSTRINGPLUSCLOB: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    INETADDRESS: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    LOCATION: ['w', 'y'],
    MULTIENUM: ['e', 'n', 'i', 'x'],
    MULTILINETEXT: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    PERCENT: ['e', 'n', 'l', 'g', 'm', 'h'],
    PHONE: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    RECORDTYPE: ['e', 'n'],
    SFDCENCRYPTEDTEXT: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    SIMPLENAMESPACE: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    STATICENUM: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    STRINGPLUSCLOB: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    TEXTENUM: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i'],
    TIMEONLY: ['e', 'n', 'l', 'g', 'm', 'h'],
    URL: ['e', 'n', 'l', 'g', 'm', 'h', 'c', 'k', 's', 'i']
};

export const operatorCodes = {
    e: 'equals',
    n: 'not equal to',
    s: 'starts with',
    c: 'contains',
    k: 'does not contain',
    l: 'less than',
    g: 'greater than',
    m: 'less or equal',
    h: 'greater or equal',
    i: 'includes',
    x: 'excludes',
    w: 'within'
};
/**
 * operator to code map
 */
export const operatorsToCodes = {
    equals: 'e',
    'not equal to': 'n',
    'starts with': 's',
    contains: 'c',
    'does not contain': 'k',
    'less than': 'l',
    'greater than': 'g',
    'less or equal': 'm',
    'greater or equal': 'h',
    includes: 'i',
    excludes: 'x',
    within: 'w'
};